# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "bou.ke/monkey"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.7.3"

[[constraint]]
  name = "github.com/gizak/termui"
  version = "2.2.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.1"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/trillian"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/pat"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.4.1"

[[constraint]]
  name = "github.com/gtfierro/go-ipfs-api"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  branch = "master"
  name = "github.com/immesys/asn1"

[[constraint]]
  name = "github.com/immesys/bw2bc"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.0.9"

[[constraint]]
  name = "github.com/multiformats/go-multihash"
  version = "1.0.8"

[[constraint]]
  name = "github.com/naoina/toml"
  version = "0.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/ucbrise/starwave"

[[constraint]]
  branch = "master"
  name = "github.com/ucbrise/vuvuzelacrypto"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.1"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "vuvuzela.io/crypto"

[prune]
  go-tests = true
  unused-packages = true
